#!/usr/bin/env node
/**
 * Synchronize the static Next.js export (`web/out/**`) into `site/**`.
 *
 * Preserves marketplace data, catalog assets, and static media in `site/` while
 * replacing hand-written HTML with content-hashed, static Next.js export output.
 * Also generates host aliases (`site/admin/index.html`, `site/admin/dashboard.html`)
 * and removes stale legacy files.
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(webRoot, "..");
const outDir = path.join(webRoot, "out");
const siteDir = path.join(repoRoot, "site");
const layoutFile = path.join(webRoot, "app", "layout.tsx");
const indexOutFile = path.join(outDir, "index.html");

const PRESERVED_FILES = new Set([
  "catalog.json",
  "explorer-data.json",
  "registry.json",
  "favicon.svg",
  ".nojekyll",
  "deployment-id.txt",
]);

function assertExportFreshness() {
  if (!existsSync(indexOutFile)) {
    throw new Error(
      "web/out/index.html does not exist. Run the build first: `corepack pnpm --dir web build`",
    );
  }
  const outMtime = statSync(indexOutFile).mtimeMs;
  if (existsSync(layoutFile)) {
    const layoutMtime = statSync(layoutFile).mtimeMs;
    if (outMtime < layoutMtime) {
      throw new Error(
        "web/out/ is older than web/app/layout.tsx. Run `corepack pnpm --dir web build` first.",
      );
    }
  }
}

function cleanStaleFiles() {
  let removedCount = 0;

  // 1. Remove previous _next directory in site
  const siteNext = path.join(siteDir, "_next");
  if (existsSync(siteNext)) {
    rmSync(siteNext, { recursive: true, force: true });
    removedCount++;
  }

  // 2. Remove temporary files if present
  const catalogTmp = path.join(siteDir, "catalog.json.tmp");
  if (existsSync(catalogTmp)) {
    unlinkSync(catalogTmp);
    removedCount++;
  }

  // 3. Clean root site files generated by export or legacy
  const siteEntries = readdirSync(siteDir, { withFileTypes: true });
  for (const entry of siteEntries) {
    if (entry.name === "assets" || entry.name === "admin") continue;
    if (PRESERVED_FILES.has(entry.name)) continue;

    const fullPath = path.join(siteDir, entry.name);
    if (entry.isFile()) {
      if (
        entry.name.endsWith(".html") ||
        entry.name.endsWith(".txt") ||
        entry.name.startsWith("__next")
      ) {
        unlinkSync(fullPath);
        removedCount++;
      }
    } else if (entry.isDirectory()) {
      if (
        entry.name === "_not-found" ||
        entry.name === "develop" ||
        entry.name === "explore" ||
        entry.name === "publish" ||
        entry.name === "submit" ||
        entry.name === "template"
      ) {
        rmSync(fullPath, { recursive: true, force: true });
        removedCount++;
      }
    }
  }

  // 4. Clean stale admin files
  const adminDir = path.join(siteDir, "admin");
  if (existsSync(adminDir)) {
    const legacyTemplateForm = path.join(adminDir, "template-form.html");
    if (existsSync(legacyTemplateForm)) {
      unlinkSync(legacyTemplateForm);
      removedCount++;
    }

    const adminEntries = readdirSync(adminDir, { withFileTypes: true });
    for (const entry of adminEntries) {
      const fullPath = path.join(adminDir, entry.name);
      if (entry.isFile()) {
        if (entry.name.endsWith(".txt") || entry.name.startsWith("__next")) {
          unlinkSync(fullPath);
          removedCount++;
        }
      } else if (entry.isDirectory()) {
        if (entry.name.startsWith("__next")) {
          rmSync(fullPath, { recursive: true, force: true });
          removedCount++;
        }
      }
    }
  }

  return removedCount;
}

function copyDirectoryRecursive(src, dest) {
  let filesCopied = 0;
  let bytesCopied = 0;

  mkdirSync(dest, { recursive: true });
  const entries = readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    // Prevent overwriting preserved catalog and registry files
    const relFromSite = path.relative(siteDir, destPath);
    if (PRESERVED_FILES.has(relFromSite)) {
      continue;
    }
    if (relFromSite === "assets" || relFromSite.startsWith(`assets${path.sep}`)) {
      continue;
    }

    if (entry.isDirectory()) {
      const sub = copyDirectoryRecursive(srcPath, destPath);
      filesCopied += sub.filesCopied;
      bytesCopied += sub.bytesCopied;
    } else if (entry.isFile()) {
      copyFileSync(srcPath, destPath);
      filesCopied++;
      bytesCopied += statSync(srcPath).size;
    }
  }

  return { filesCopied, bytesCopied };
}

function writeAliasesAndMarkers() {
  // Aliases for admin
  const adminHtml = path.join(siteDir, "admin.html");
  if (existsSync(adminHtml)) {
    const adminDir = path.join(siteDir, "admin");
    mkdirSync(adminDir, { recursive: true });
    copyFileSync(adminHtml, path.join(adminDir, "index.html"));
    copyFileSync(adminHtml, path.join(adminDir, "dashboard.html"));
  }

  // Ensure directory index.html aliases exist for subroutes if the folder exists
  const adminDir = path.join(siteDir, "admin");
  if (existsSync(adminDir)) {
    const entries = readdirSync(adminDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".html") && entry.name !== "index.html") {
        const subName = entry.name.slice(0, -5);
        const subDir = path.join(adminDir, subName);
        if (existsSync(subDir) && statSync(subDir).isDirectory()) {
          copyFileSync(path.join(adminDir, entry.name), path.join(subDir, "index.html"));
        }
      }
    }
  }

  // Ensure .nojekyll exists
  const nojekyll = path.join(siteDir, ".nojekyll");
  if (!existsSync(nojekyll)) {
    writeFileSync(nojekyll, "# Prevent GitHub Pages Jekyll processing\n", "utf8");
  }
}

function main() {
  console.log("export-to-site: verifying build freshness…");
  assertExportFreshness();

  console.log("export-to-site: cleaning previous generated files in site/…");
  const removed = cleanStaleFiles();

  console.log("export-to-site: copying web/out/ to site/…");
  const { filesCopied, bytesCopied } = copyDirectoryRecursive(outDir, siteDir);

  console.log("export-to-site: writing host aliases and .nojekyll…");
  writeAliasesAndMarkers();

  const mb = (bytesCopied / (1024 * 1024)).toFixed(2);
  console.log(
    `export-to-site complete: ${filesCopied} files copied (${mb} MB), ${removed} stale entries removed.`,
  );
}

main();
